version: "3.7"
services:
        minecraft-server:
                image: minecraft-server:v1
                ports:
                        - "25565:25565"
                        - "11111:11111"
                volumes:
                        - /home/max/craftaeder/server-data:/opt/data
                environment:
                        JVM_ARGS: "-Xmx4G -Xms4G"
                stdin_open: true
                tty: true
